### ISSUE TITLE
Continuation of taghelper into partials

### ISSUE THREAD

**Issue by LyonBlecher** [contentful/contentful.net#114]
I have a tag helper markup  like so
```
</panel> 
<panel-row>
            <label asp-for="ServerInitSettingsModel.ApplicationName"></label>
            <div>@(Model.ServerInitSettingsModel.ApplicationName)</div>
        </panel-row>
        @{
            Html.RenderPartial("_CustomSettings", Model.ServerInitSettingsModel.CustomSettings);
        }
        <panel-footer></panel-footer>
    </panel>
```

I would like to be able to inject a partial view with more rows based on custom settings, but the tag-helper markup in the partial is not recognized and therefore doesn't render correctly.  The partial view is:

```
@model Dictionary<string, string>

@foreach (var custom in Model)
{
    <panel-row>
        <label>@custom.Key</label>
        <div>@custom.Value</div>
    </panel-row>
}
```

**Comment by Roblinde** [comment]
Hi Lyon

That sounds interesting, but I'm not quite sure what that has to do with this repository?

Have you tried using a ViewComponent instead of a partial view? https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components

Are you using Contentful for this project?

Is there anything specifically related to the SDK that I can help you with?

Best
Robert

**Comment by LyonBlecher** [comment]
My apologies I thought I was somewhere else ;)
Sorry to waste your time!

**Comment by Roblinde** [comment]
No worries, you're welcome here any time 😄 

Cheers!
