### ISSUE TITLE
Queries that return more than one reference to the same entry result in missing data

### ISSUE THREAD

**Issue by lance-h** [contentful/contentful.net#139]
When an entry is referenced by multiple other entries, only the first entry is populated. The subsequent entries only contain a single $ref node.

For example, we have a content-type called "Navigation" which can reference one or more "Page" content-type entries. A page can also reference other pages by way of a reference field.

When using the SDK to return multiple levels we have found that only the first instance of a reference is deserialized. All other instances are deserialized as null.

This seems to occur because all entries that have been previously processed by the ContentfulClient are replaced with a JObject containing a single $ref node here: https://github.com/contentful/contentful.net/blob/master/Contentful.Core/ContentfulClient.cs#L292

The $ref never seems to be be used anywhere, although it does appear that Asset references make use of this.

Removing the following lines of code resolves the problem for us however it is likely going to affect performance (I'm assuming that the purpose of this pattern was to avoid using extra memory by duplicating identical nodes):

```
if (processedIds.Contains(linkId))
{
  replacementToken = new JObject
   {
      ["$ref"] = linkId
   };
} else
```

**Comment by Roblinde** [comment]
Hi Lance

This is indeed intentional and is to avoid circular references and to save memory in general. The `$ref` pattern is used internally by Newtonsoft.Json https://www.newtonsoft.com/json/help/html/PreserveObjectReferences.htm

However, it should not deserialize to null unless you're not using strongly typed objects, in which case you would have to resolve the reference yourself.

There is one other caveat surrounding this and that is if you have a reference previously in your json structure that gets the `$id` token that you do not deserialize. In those cases the `$ref` does not know find a deserialized object to use. To get around this you can set `ResolveEntriesSelectively` on your client just prior to calling `GetEntries` and it will only deserialize properties available in your type.

Are you deserializing to a strong type or to dynamic?

**Comment by lance-h** [comment]
OK fantastic - `ResolveEntriesSelectively = true` has resolved the problem. The scenario is exactly as you describe in your caveat - we have some data being returned by the API which we are not deserializing. Ideally we wouldn't have this extranneous data (something for our team to resolve) but it's good to know there is a simple work around.

Thanks for your help.

**Comment by Roblinde** [comment]
That's great to hear!

Just let us know if we can help you out with anything else.
