### ISSUE TITLE
ManagementClient: Create Entry with specific ID

### ISSUE THREAD

**Issue by lance-h** [contentful/contentful.net#154]
The Contentful API provides a way to create an entry with a specific ID

>When creating resources, you can specify an ID or let the API generate a random ID for you. If you choose an ID yourself it must adhere to the following rules
See https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/resource-ids

Is this possible to achieve with the ManagementClient?

**Comment by Roblinde** [comment]
Hi Lance!

Yes, you can achieve this by using the `CreateOrUpdateEntry` method instead of `CreateEntry`. There's also the `CreateEntryForLocale` method that allows you to pass an object and use its properties to create an entry for a specific locale, this can be convenient if you only have one locale in your space.

Let me know if you need more examples.

**Comment by lance-h** [comment]
Thanks again @Roblinde - looks like I was accidentally using the wrong overload of CreateOrUpdateEntry. This is working for me now - I can see PUT requests firing happily.
