### ISSUE TITLE
Creating Rich Text from HTML

### ISSUE THREAD

**Issue by jerriep** [contentful/contentful.net#169]
I see there is an `HtmlRenderer` class that allow users to convert from a `Document` to HTML. Is there anything that does the conversion in the other direction?

I am sitting with HTML which I want to upload into a RichText field using the `CreateOrUpdateEntry` method. How do I go about doing this?

**Comment by Roblinde** [comment]
There's unfortunately no support to turn HTML into a rich text structure at the moment. You would have to parse the HTML yourself and create a `Document` object and fill it with `IContent` of the appropriate type.

For example, consider the following super simple HTML snippet:

```
<p>Hello world!</p>
```

To turn that into a rich text format you'd do something like:

```
var doc = new Document();
doc.NodeType = "document";
doc.Content = new List<IContent>();

var paragraph = new Paragraph();
paragraph.NodeType = "paragraph";
paragraph.Content = new List<IContent>();

var text = new Text();
text.NodeType = "text";
text.Value = "Hello world!";
text.Marks = new List<Mark>();

paragraph.Content.Add(text);
doc.Content.Add(paragraph);
```

Hope this helps a bit.

**Comment by jerriep** [comment]
That helps @Roblinde. One more question though:

How to I set the value of a Rich Text field when calling the `CreateOrUpdateEntry` method? I tried the following:

```cs
var entry = new Entry<dynamic>
{
    SystemProperties = new SystemProperties()
};
entry.SystemProperties.Id = entryId;
entry.Fields = new Dictionary<string, object>();
entry.Fields["title] = new Dictionary<string, string>
{
    {locale, "This is the title"}
};
entry.Fields["rtField"] = new Dictionary<string, object>
{
    {locale, doc}
};

await client.CreateOrUpdateEntry(entry, contentTypeId: settings.ContentTypeId, version: latestVersion);
```

But that gives me this error:

```
Contentful.Core.Errors.ContentfulException: Validation error[
  {
    "name": "required",
    "details": "The property \"data\" is required here",
    "path": [
      "fields",
      "rtField",
      "en-US",
      "content",
      0,
      "data"
    ]
  },
  {
    "name": "required",
    "details": "The property \"data\" is required here",
    "path": [
      "fields",
      "rtField",
      "en-US",
      "data"
    ]
  }
]
```

**Comment by Roblinde** [comment]
You are absolutely right, it seems the strictness of the type checking as been changed since I last did this. This makes most of the types in the SDK unusable for actually creating rich text documents. Almost every node in the rich text structure has the `data` property, and in almost all cases this is just an empty object, which is why I initially didn't add them to nodes where it wasn't used. Turns out to be a mistake in hindsight. 

Sadly I don't have a lot of time to work on updating the SDK currently. I think the easiest way forward for you at the moment would be to use anonymous objects or dynamic that adhere to the current rich text schema.

For example for a document with an empty paragraph:

```
var doc = new { nodeType="document", content=new List<object>(), data=null  };
doc.content.Add(
   new { nodeType="paragraph", content=new List<object>(), data=null }
)
```

I will see if I can look into improving this experience going forward. It shouldn't be too big of a change to write ethier a custom serializer or add a `Data` property in the appropriate places.

I'll keep this issue open while investigating.

**Comment by afreenh** [comment]
Hello, 

I'm also facing similar issue where I want to update 'Rich Text' using CM API. I have also tried same code snippet mentioned above But i'm getting different error: 

Message: Cannot create an instance of an interface.
Stack Trace: at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Contentful.Core.Configuration.ValidationsJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\projects\contentful.net\Contentful.Core\Configuration\ValidationsJsonConverter.cs:line 128

I have observed that Document/Paragraph/Text classes do not have 'data' property. What is the significance of 'data' here & every nodeType has this additional blank node ? 

Really appreciate your help here.

Thanks,
Afreen

**Comment by Roblinde** [comment]
Hi Afreen

There are two things here, firstly you're trying to instantiate an IFieldValidator it seems. You can't do that, but must instead instantiate a concrete implementation of IFieldValidator, such as a RangeValidator or RegexValidator.

Secondly is the issue with the `data` type. This empty node is unfortunately required by the underlying API and this means that you can't use the out of the box classes, but rather would have to do something along the lines of my example above.

**Comment by afreenh** [comment]
Thanks for looking into the above issue. I'm able to convert markdown/html into Document Json using below package: 
https://github.com/contentful/rich-text/tree/master/packages/rich-text-from-markdown

{"nodeType":"document","data":{},"content":[{"nodeType":"paragraph","content":[{"nodeType":"text","value":"This is test rich text testing for NMN","marks":[],"data":{}}],"data":{}}]}

Now, How do I pass it back to contentful using CM API ? Because when I'm trying to do deserialize it into Document (Contentful.Core.Models), I'm getting error "Could not create an instance of type Contentful.Core.Models.Content. Type is an interface or abstract class and cannot be instantiated". 

Any help would be really appreciated? Our project is going to production & this is critical issue for us.

**Comment by Roblinde** [comment]
@afreenh if you already have it as a `JObject` in .NET you could just pass that as a property on your type and it should be fine.

However, I've made some progress on this during the week and have an updated package that can pass a document structure back. Hopefully I will be able to get around to releasing it next week.
I'm also working on an F# package that grabs an HTML structure and turns it into well formatted JSON that the Contentful API expects... It'll be a little bit before I can get that into some sort of alpa release.

**Comment by Roblinde** [comment]
I have now built a small package that can parse simple html to a rich text structure: https://robertlinde.se/posts/parsing-html-to-contentful-rich-text/

This will be the answer for now, I will continue working on that package when I have the time and add support for images etc.

Let me know if this helps you any @jerriep @afreenh

**Comment by jerriep** [comment]
Great stuff. Thanks for sorting this out @Roblinde 

Regarding images. In your blog post you state:

> One glaring omission here is <img>-tags, which I haven't handled yet as I haven't fully decided on the strategy. Should the package help you create an asset or should it let you define your own callback for other custom tags you want to handle? I'll ponder this for the next version.

I would like it if I had a choice in how to handle this, so I would prefer some sort of callback mechanism.

**Comment by jerriep** [comment]
@Roblinde I started playing around with your Nuget package to convert HTML to Rich Text but I am running into issues with Unordered Lists. The node type hierarchy for unordered list items should be `unordered-list` -> `list-item` -> `paragraph` -> `text`, but your package generates it as `unordered-list` -> `list-item` -> `text`. 

Is this package source code open source so I can look into it?

**Comment by Roblinde** [comment]
@jerriep you're right! My mistake, I'll add the paragraph in between. I haven't open sourced the package yet, but will do it shortly. Was hoping to improve the handling of images first.

**Comment by Roblinde** [comment]
hmm, turns out this is just annoying... the rich-text parser right now creates a structure json-structure identical to the HTML input, but the Contentful rich-text format only allows text nodes to be child of paragraphs, which _forces_ every list item to contain a paragraph, which in turn if you want to turn the rich text back into html might well ruin your design. This is a mistake in the implementation of the rich-text format in my opinion and will lead to some messy code to workaround... I'll have to give it some thought, I'll get back to you.

**Comment by Roblinde** [comment]
Put up a new version of the package on NuGet now. It should workaround the list item problem and also adds the possibility to add inject custom parsers into the pipeline.

**Comment by jerriep** [comment]
Thanks Rob. I have switched over to another task again :) Will hopefully be able to swing back to this next week. Will let you know if I have issues.

**Comment by jerriep** [comment]
Hi @Roblinde , I finally had an opportunity to look at this again, and it seems to be much better and handle the lists fine now.

Any progress on handling images? 

As mentioned previously, I would like some sort of control over specifying the reference to images, since I handle the uploading of images separately and just want to just pass the asset ID somehow.

**Comment by jerriep** [comment]
@Roblinde Just pinging again about this. Are you still working for Contentful on this?

**Comment by tschellenbach** [comment]
+1

**Comment by AlexAvlonitis** [comment]
For anyone interested, I started building a **ruby** gem https://github.com/AlexAvlonitis/contentful_converter . It's still WIP

**Comment by stephenhmarsh** [comment]
thank you @AlexAvlonitis -- just used it in a lil data migration script and it works beautifully

**Comment by Eagleye126** [comment]
Hey all. I stumbled on this issue and tried to find a way to do this in python.
after seeing there is nothing written in python, I managed to solve this by creating REST api in js.

I saw this [stackoverflow ticket](https://stackoverflow.com/a/62022004/12042016) that helped me to get to this solution:

```
const { richTextFromMarkdown } = require('@contentful/rich-text-from-markdown');
var TurndownService = require('turndown')

var turndownService = new TurndownService()
const express = require('express');
const bodyParser = require('body-parser');

const port = 3000;
const app = express();

app.use(express.json());
app.use(bodyParser.urlencoded({
  extended: true
}));

app.post('/html-to-rich-text', async (req, res) => {
  console.log("body", req.body)
  var markdown = turndownService.turndown(req.body.html)
  const richText = await richTextFromMarkdown(markdown)
  console.log("resp", richText)
  res.send(richText);
});


app.listen(port, () => {
  console.log(`HTML to RichText server listening at http://localhost:${port}`)
});
```

That way I was able to continue enjoy writing the rest of the project in python, and still get this missing capability 
I hope that someone could use this one day :)
