### ISSUE TITLE
Media of type image mapping Asset to simplified Class

### ISSUE THREAD

**Issue by thepra** [contentful/contentful.net#197]
When I query for the `Asset` which is just an image I would to have it mapped to a simpler custom `Class` like:
```
    public class Image {
      public string Url {get;set;}
      public string Title {get;set;}
      public string Description {get;set;}
    }
```
I didn't found in the documentation any way to map/simplify the contentful sdk native classes to something simpler. 

Is there any way to do this?

**Comment by Roblinde** [comment]
Hi @thepra, thanks for the question. 

To achieve this you would have to write a custom jsonconverter https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm
for your Image class above and add it to the `SerializerSettings` och your `IContentfulClient`. Something like: `_client.SerializerSettings.Converters.Add(yourConverter)`

Then you can just fetch your entries normally and make sure your classes use your `Image` class instead of the `Asset` wherever appropriate.

Hope this helps you move forward..
