### ISSUE TITLE
Are all of the dependencies required?

### ISSUE THREAD

**Issue by ahmettaha** [contentful/contentful.net#21]
Hello,

For .net 4.6.1 applications, nuget installs a lot of dependencies, and some of the required updates such as System.Net.Http 4.1.1.0 cause incompatibilities with other libraries. Are all of these libraries really required?

**Comment by Roblinde** [comment]
Hi Ahmet!

The core SDK has in reality three separate dependencies. 

- Newtonsoft.Json
- Microsoft.Extensions.Options
- NetStandard.Library

These have in turn their own dependencies in a rather large graph, especially for the NetStandard.Library which is where the System.Net.Http package is included for example. 

All of these libraries are required in the sense that they are part of the NetStandard.Library. That said I'm sure you could use binding-redirects for minor versions of packages. You can read more about how that works here: https://msdn.microsoft.com/en-us/library/eftw1fys(v=vs.110).aspx

What do you mean by required updates? Does some other library require an update in order to work correctly?

Let me know if there's anything I can do to help.

**Comment by ahmettaha** [comment]
Hello

Netstandard is the problem. It updates system.net.http to 4.1.1.0 and it has the following problem

https://github.com/dotnet/corefx/issues/11100

This problem for example breaks identity server. To fix it we need to manually change the binding redirect to a lower version 4.0.0. But because we change it manually, whenever there is a nuget update, it updates the bibding redict to 4.1.1 and it becomes broken again.

**Comment by Roblinde** [comment]
Ah, yes I understand that this is a pain to deal with 😞 

Have you tried the steps suggested in the comment here: https://github.com/dotnet/corefx/issues/11100#issuecomment-246469893

I'm not sure what we can do on our end to alleviate this, but I'll make sure to follow the microsoft issue and as soon as there's a workaround in place make sure that we implement it or update to a package that does not have this problem.

**Comment by ahmettaha** [comment]
I prefer not to alter settings to overcome this bug. Most likely, I'll just write my own client to query the data for now.

thank you.

**Comment by Roblinde** [comment]
I understand, I will leave this issue open and notify you as soon as a fix from Microsoft is available.

**Comment by Roblinde** [comment]
Hi Ahmet, 

according it seems the issue might have been resolved in https://github.com/dotnet/corefx/issues/11100#issuecomment-281476889

I have not yet been able to confirm, but if you wish to try to update to that version of System.Net.Http it might resolve the problem for you.

**Comment by Roblinde** [comment]
Closing this, it seems to be resolved with the latest version of System.Net.Http
