### ISSUE TITLE
`Snapshot` property missing on SnapShot class?

### ISSUE THREAD

**Issue by andersekdahl** [contentful/contentful.net#210]
This class: https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Models/Management/SnapShot.cs

Seems to be missing the `snapshot` data from the API response. Is this intentional or something that will get fixed?

**Comment by andersekdahl** [comment]
To be a bit more clear, the snapshot response contains:
```
{
  sys: ...
  snapshot: {
    sys: ...,
    fields: ...
  }
}
```
But by looking at this code:
https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Configuration/SnapshotJsonConverter.cs#L47-L48

It seems that `SnapShot.SystemProperties` is set to the outer `sys` property and not `snapshot.sys` which is what at least I need when working with a snapshot.

**Comment by Roblinde** [comment]
That looks like a bug. It's probably been there since forever. I'll get it fixed in the next version. Thanks for reporting it.

**Comment by Roblinde** [comment]
Actually on further investigation, the outer sys object is actually the sys properties of the snapshot, so that is correctly set. But the inner sys-properties contains the sys properties for the snapshotted entity (for example the entry) and this would also need to be exposed. My thinking is exposing a new property on the Snapshot-class called EntityProperties or something of that nature that will contain the sys properties of the inner entity. Do you think that'd work for you?

**Comment by andersekdahl** [comment]
Works for me, makes sense that you'd want to include both!

**Comment by Roblinde** [comment]
Version 5.0.2 should be available shortly.
