### ISSUE TITLE
Null for reference when shared with an entry that doesn't have a resolver

### ISSUE THREAD

**Issue by FreshRob** [contentful/contentful.net#275]
Hi,

Come across an issue where by in the RichText if an entry has a reference to an author but no resolver and said author is referenced by another entry that has a resolver then the property is null.

```txt
paragraph
entry-with-no-resolver {
    author: authorb
}
paragraph
entry-with-a-resolver {
  author: authorb
}
```

I assume this is to do with processedIds inside the contentfulClient, as the first one doesn't have a resolver so the author referenceId is marked as processed and stored as null.

Does that sound about right?

I can look into it, but thought I would verify before trying to make any changes there

**Comment by Roblinde** [comment]
Hmm sounds like it could be the same issue that I explain here https://robertlinde.se/posts/why-is-my-item-null-contentful-net/ have you tested with `ResolveEntriesSelectively=true`. Hopefully that resolves it, otherwise we'll have to go deeper and investigate why we can't seem to find the correct item to deserialize from.

**Comment by Roblinde** [comment]
Possibly related to #277

**Comment by FreshRob** [comment]
Sorry I took so long to get back to this, yes that solved the issue thank you.
Is there a performance hit from this setting?

**Comment by Roblinde** [comment]
@FreshRob yes, there is a small performance hit as the SDK needs to use reflection to inspect the types during deserialization. It should be very small however.
