### ISSUE TITLE
Null reference exception when rendering rich text content with a couple of content elements sharing the same asset

### ISSUE THREAD

**Issue by Pliuxus** [contentful/contentful.net#277]
Hi,

I have a content item that has a rich text field into which I'm embedding another content item (different type) having a media field, populated by a draft image. Then in the same rich text field I've embedded the same image as an asset. With this setup, when I'm rendering this content on a page using `<contentful-rich-text document/>` tag, I'm getting a null reference exception here:
> Contentful.Core.Models.AssetRenderer.RenderAsync(IContent content) in Authoring.cs
`if (nodeType != "asset-hyperlink" && asset.File?.ContentType != null && asset.File.ContentType.ToLower().Contains("image"))`

Here's the content setup (an embedded entry and an embedded asset):
![image](https://user-images.githubusercontent.com/47353290/146561221-6628960f-d030-4fe5-ae3b-ec0bbdafcfe3.png)

**Comment by Roblinde** [comment]
Hi @Pliuxus thanks for the report. This sounds interesting. Not sure if using `ResolveEntriesSelectivley=true` solves this, but it's almost certainly related to what i describe here: https://robertlinde.se/posts/why-is-my-item-null-contentful-net/

If setting `ResolveEntriesSelectivley=true` doesn't solve this problem for you I'll look into setting up a similar setup and investigate.

**Comment by Pliuxus** [comment]
Thanks, @Roblinde. Unfortunately it did not help, still getting the same null reference exception right here:
![image](https://user-images.githubusercontent.com/47353290/146907260-dac859d0-059e-4541-b4fc-213b3f0b41d7.png)

**Comment by Roblinde** [comment]
@Pliuxus sorry for taking some time to get around to this. I have investigated now and been able to reproduce the problem. I will fix so that this does not throw an exception in an upcoming fix. However, the problem is related to the blog post I alluded to earlier. What you need to do here is to instruct the serializer through a ContentTypeResolver how you want to resolve the entry-reference that you are inserting. (See https://www.contentful.com/developers/docs/net/tutorials/using-net-cda-sdk/#get-entries-of-multiple-types-or-by-interface for an example implementation.) 

Once you have instructed it how to serialize the entry the asset should also be able to resolve without a problem.

Let me know if you need any help with getting it working.
