### ISSUE TITLE
Response size too big. Maximum allowed response size: 7340032b

### ISSUE THREAD

**Issue by steuraa** [contentful/contentful.net#286]
Hello,
I'm running in to this error when I try to retrieve a single contentful entry via client.GetEntries()
`var queryBuilder = QueryBuilder<Inspiration>.New.Include(4) .ContentTypeIs("inspiration").FieldEquals(f => f.sys.Id, id).Build();`
`var result = await client.GetEntries<Inspiration>(queryBuilder + $"&locale={locale}");`

I assume the issue is the Include(4), but we need this to get all the relevant data for that entry.
Is there a way to increase the maximum allowed response size?

Best regards

**Comment by Roblinde** [comment]
Hello @steuraa  

This is unfortunately a limitation of the underlying API and not something you can control from the SDK. What you could try to limit the response size (since lowering the Include-level seems to not be an option) is to use the Select operator https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator/query-entries/console/dot-net and make sure you select only the properties you really need. 

Except that I'm afraid there's no option other than making multiple separate requests to lower the amount of data in each.
