### ISSUE TITLE
Deserializing response that references same content twice in to different objects throws System.ArgumentException: The value "Type" is not of "Expected type"

### ISSUE THREAD

**Issue by Msigvartsen** [contentful/contentful.net#307]
Hi, 

I'm having some issues deserializing my response from Contentful when the same content is referenced in different content types in the response.

I have a LinkItem Content type that references  “MyContent”. This is deserialized in to a object called InternalReference, which contains a slug field. 

I also have a teaser section component that references the same content type “MyContent”, called ContentTeaser. 

This gives me an exception that the value “InternalReference” does is not of type “ContentTeaser”. 

I assume this is because the item is already dereferenced and is expected to be of the first type? 
Is there a fix, or a work around I can use for this? 

It`s working as expected if I either remove one of the fields to deserialize (Content teaser or InternalReference object), or if I use the same object in both places.

Thanks! 

- Magnus

**Comment by Msigvartsen** [comment]
This is package contentful.csharp version 7.2.3

**Comment by Roblinde** [comment]
Hi @Msigvartsen you're correct, it's because the item has already been deserialized into another object type. You could solve this by using a baseclass I believe, so that `ContentTeaser `inherits `InternalReference`. I'm not entirely sure how Json.NET handles the properties that are not part of the base class in that case. 

You could also use an interface together with a content type resolver, like here: https://www.contentful.com/developers/docs/net/tutorials/using-net-cda-sdk/#get-entries-of-multiple-types-or-by-interface

Hope this helps you get on the right track.

**Comment by Msigvartsen** [comment]
Sorry for the delayed response @Roblinde. 
Got it working using a baseclass for these entries in question

**Comment by Roblinde** [comment]
Glad to hear it!
