### ISSUE TITLE
Allow better control over what types are created when deserializing.

### ISSUE THREAD

**Issue by Roblinde** [contentful/contentful.net#45]
A suggestion would be to maybe use JSON.Net type handling to allow to specify how certain content types should be deserialized: http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm

A suggestion would be to have an `IContentTypeResolver` that the user can implement that returns a type for a given content type.

See suggestion in this PR #44

**Comment by Roblinde** [comment]
I've been looking into this a bit and it's not entirely trivial to implement this using TypeNameHandling (http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm) in Json.Net, mostly due to all the other logic inside the GetEntries methods.

To avoid complicating the codebase I'm leaning towards recommending using a custom JsonConverter that you implement on the consuming side.

Say for example that you have 3 classes that you want a call to GetEntries to deserialize into, A, B and C. Simply implement an interface for all three classes, add a custom jsonconverter to the interface and make your call to GetEntries with the interface. Something like: `var entries = client.GetEntriesAsync<IMarker>()`.

What do you think @aKzenT @simplyio ?

**Comment by aKzenT** [comment]
That is exactly what I do at the moment to support that scenario. It does however have some drawbacks since JsonConverter are a bit limited by design. Besides having to implement the marker interface, you also have to handle all the extra stuff in your converter like $id/$ref handling.

Where do you see the problems handling this with TypeNameHandling?

My thought was to either: Write a fake $type with just the content type name and then have a custom SerializationBinder which resolves this to the actual type to deserialize into (with the mapping provided by the consumer of the library in some way).

Or: Map the content type directly to a .NET type and write this type information into the $type property, letting the DefaultSerializationBinder take care of the rest.

**Comment by Roblinde** [comment]
ah yes of course, the $id/$ref part is a pain. Didn't think of that.

The main issue with adding more logic to the GetEntries method is that it's already overly complex I feel. (which is mainly my fault as I change the json structure etc.) I'll look into it some more today and see if I can come up with a way to refactor it to make the $type fit in more cleanly.

My though was this:

Add an `IContentTypeResolver` interface.

Add a `public IContentTypeResolver ContentTypeResolver { get; set; }` to the clients to allow the consumer to specify a type for a contenttypeid.

At deserialization time add $type for any entry that has a matching contenttype id.

**Comment by Roblinde** [comment]
I've added this branch just now: https://github.com/contentful/contentful.net/tree/feature/add-contenttype-resolver

I still have some more testing to do, like what happens if you add a resolver and have a deep nested structure where many `$ref` properties will be added. But it seems to be working fine from my tests.

What do you think of this approach? @aKzenT

**Comment by aKzenT** [comment]
Looks good!

**Comment by Roblinde** [comment]
This is now in the latest version! Let me know how it works for you!
