### ISSUE TITLE
Implement Serialization in AssetJsonConverter

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#50]
Current the AssetJsonConverter only supports reading JSON, but not writing it.

This is usually not a problem, since contentful.net is only parsing the JSON returned from the CMS. However quite often you want to save the models returned from the library in some other system. E.g. in our case we cache instances in redis. Other use cases might include storing objects in the user session or even serializing them to disk.

Now the problem is that the serialization uses the default JSON.NET serialization, but deserializing will always use the deserialization of the AssetJsonConverter since it is declared on the type. This will obviously crash as the deserialization format differs significantly from the default serialization layout created by JSON.NET.

An alternative would be to remove the AssetJsonConverter from the Asset type and add the converter manually during the deserialization process by using custom JsonSerializerSettings.

My preference would be to do both, so that the user can decide what serialization mechanism he wants to use. It might also be worth to check if there is a way to define the asset class in a way that does not require a custom converter at all.

Thank you!

**Comment by Roblinde** [comment]
Ah, interesting problem.

There is another class in the SDK `ManagementAsset` that could be used instead that allows for both reading and writing. It is a bit annoying to work with though as it wraps each property in a dictionary since each property can exist in multiple locales. So you'd go `asset.Title["en-US"]` or `asset.Title["de-DE"]` to retrieve the property in the specific locale.

However, removing the converter certainly sounds like a good option. I'll look into that as well.

**Comment by aKzenT** [comment]
By using SerializationSettings, it is easy to avoid this by moving the converter to the default SerializationSettings of the class. See also pull request for #51

**Comment by Roblinde** [comment]
This should be working now as well in the latest version. Let me know if it works as you expect.
