### ISSUE TITLE
CreateEntryAsync CamelCasePropertyNamesContractResolver fails if field.Id isn't camelcase

### ISSUE THREAD

**Issue by mercedesb** [contentful/contentful.net#61]
The ContentfulManagementClient.CreateEntryAsync uses the CamelCasePropertyNamesContractResolver which causes the request to fail if the field in Contentful doesn't have camelcase ids because the CMA can't find any properties with a matching id.

I defined a content type via code where the Entry title field was "Title" (the id of the field was also "Title"). When trying to create an instance of this entry via the SDK, I received an exception about being unable to find a field with id 'title.' I tested changing the field id to 'title' and my request worked as expected.

I'm not sure the best way to resolve this. Add some validation requiring that the id of a field be camel case? Or remove that contract resolver and rely on the developer to send in their request correctly cased? Or make it case insensitive?

**Comment by Roblinde** [comment]
There are several ways to solve this, but the simplest is probably just using a `JsonProperty` attribute on your property.

```csharp
[JsonProperty("Title")]
public string Title { get; set; }
```

If you wish to change the default contract resolver you can do so by providing the client with your own `JsonSerializerSettings`.

```csharp
var client = new ContentFulManagementClient(httpclient, options);
client.SerializerSettings = new JsonSerializerSettings 
   {
      //Add your custom settings... 
   }
```
Hope this helps!

**Comment by Roblinde** [comment]
hmm, I'm getting confused. It seems to be working for me to both serialize from a capitalized property and not. Let me know if the issue persists and I'll look more closely.

**Comment by mercedesb** [comment]
Interesting, thanks for the pointers! I was seeing a lot of weird behavior yesterday so maybe I did something wrong. Thanks for taking a look!

**Comment by Roblinde** [comment]
No problem, just let me know if I can be of assistance.

**Comment by mercedesb** [comment]
I ran into this issue again. I still think it's the CamelCasePropertyNamesContractResolver in ContentfulManagementClient.CreateEntryAsync but maybe I'm doing something wrong. If I define a content type as follows:

```
> [ContentType(Name = "Room Reservation", DisplayField = "subject")]
>     public class RoomReservation : BaseEntry
>     {
>         [ContentField(Name = "Reserved By", Required = true, Type = SystemFieldTypes.Symbol)]
>         [JsonProperty("reservedBy")]
>         public string ReservedBy { get; set; }
>    // ... omitted for brevity
> }
```

When I call `Entry<dynamic> created = await mgmtClient.CreateEntryAsync(toCreate);` I get a Contentful.Core exception that it can't find a field with the Id 'reservedBy.' When creating the dynamic object, it doesn't matter if the json is serialized to `ReservedBy` or `reservedBy` because the Id of the property in the web app is ReservedBy but the ContentfulManagementClient serializes it as reservedBy which doesn't exist.

**Comment by Roblinde** [comment]
Ah yeah, there could still be an issue if you're adding fields to an `Entry<dynamic>` I'm suspecting. What does your code look like when creating the actual entry?

**Comment by mercedesb** [comment]
```
 public static Entry<dynamic> GetDynamicEntry<T>(this T model, string locale = "") where T : IContentType
        {
            if (string.IsNullOrWhiteSpace(locale))
                locale = "en-US"; // TODO: set to space's default locale

            Entry<dynamic> entryWrapper = new Entry<dynamic>();
            //TODO: better way to handle this?
            if (model is BaseEntry)
                entryWrapper.SystemProperties = (model as BaseEntry).Sys;

            // need to get locales (waiting to hear from Contentful)
            var fields = new ExpandoObject() as IDictionary<string, object>;

            PropertyInfo[] props = model.GetType().GetProperties();
            Dictionary<string, object> localeValues;
            foreach (var prop in props)
            {
                if (prop.GetSetMethod() == null || prop.GetCustomAttribute<IgnoreContentFieldAttribute>() != null)
                    continue;

                localeValues = new Dictionary<string, object>();
                localeValues.Add(locale, prop.GetValue(model));
                fields.Add(prop.Name, localeValues);
            }
            entryWrapper.Fields = fields;

            return entryWrapper;
        }
```

`IContentType ` is an interface I'm using in my project that just has some getters for easier access to Content Type props (like id and name)

**Comment by Roblinde** [comment]
Yes, I see.

The problem here is that when you create your dynamic representation of your object the `JsonProperty` attribute is not respected as it's part of your `RoomReservation` and not the dynamic you're creating.

So when you call `fields.Add(prop.Name, localeValues);` you're saying `fields.Add("ReservedBy", ...);` 

What you could do is check if the property has a `JsonProperty` attribute and in that case get the value of the property from that attribute instead.

Something along the lines of this:

```csharp
var attributeData = prop.CustomAttributes.First(c => c.AttributeType == typeof(JsonPropertyAttribute));

var propertyName = attributeData.ConstructorArguments.FirstOrDefault().Value?.ToString();

if (propertyName == null)
    {
        propertyName = attributeData.NamedArguments.FirstOrDefault(c => c.MemberName == "PropertyName").TypedValue.Value?.ToString();
    }
```

Another approach would be to have a separate class to use for creation of the content type. Something like:

```csharp
     public class RoomReservationManagementEntry
     {
         [JsonProperty("reservedBy")]
         public Dictionary<string, string> ReservedBy { get; set; }
 }
```

and then at creation time:

```csharp
var fields = new RoomReservationManagementEntry();
fields.ReservedBy = new Dictionary<string,string> { { "en-US", "banana" }  };

var entry = new Entry<dynamic>();
entry.Fields = fields;

client.CreateEntryAsync(entry, contentTypeId: "content-type");
```

And I think here the JsonProperty would be respected as you're passing the actual object and not just the propertyname.

BTW is this something I've missed: `// need to get locales (waiting to hear from Contentful)`, what about locales?

**Comment by mercedesb** [comment]
No you didn't miss anything, I was waiting to hear from sales about our agency account that has access to the localization feature. I haven't gotten around to that yet though, forgot to room the parentheses :)

What I'm seeing is during my testing is whether I serialize the json to `{ ReservedBy = "Mercedes" }` or `{ reservedBy = "Mercedes" }` I always get a Contentful.Core exception because the Id is 'ReservedBy' in the Contentful Web App and the code always looks up 'reservedBy' regardless of the object I sent in.

**Comment by Roblinde** [comment]
ah, I see. I never did look at serialization only deserialization, might be why I've missed it. I'll look at it right away and see what gives.

**Comment by Roblinde** [comment]
Ops, my suggestion of adding a check for custom attributes won't work I'm afraid. The suggestion of a separate class with JsonProperty-attributes will work though.

I forgot that I added a `CamelCasePropertyNamesContractResolver` specifically in the `ConvertObjectToJsonStringContent` even though you reminded me I thought you just meant the standard Json.Net setting. Not until I dived in now did I really understand what you meant, sorry about that.

Anyway, you're absolutely correct that it won't matter if you put `{ ReservedBy = "Mercedes" }` it will still be put to `reservedBy` by the ContractResolver. The problem if we remove it though, is that then you'd have to either have lower case properties in your c# classes (we don't like that) or you'd have to set `JsonProperty` all over the place which is also nasty.

I think the default is good as it is, buuut the problem is if you pass an object that does not have a `JsonProperty` then it will always be lowercased. My second workaround works well though, although it means you'd have to create a specific class for your managementobjects to add the attribute to.

What are your thoughts?

**Comment by mercedesb** [comment]
Yeah, your second work around works and doesn't seem to have the drawbacks of the other options. I'm going to play with this some more to see if there's anything else that can be done but this resolves the weird issues I was seeing. Thanks for walking through this so thoroughly!!

**Comment by Roblinde** [comment]
My pleasure, let me know if anything else pops up.
