### ISSUE TITLE
weak support for Xamarin.Forms PCL and NetStandrad

### ISSUE THREAD

**Issue by tombby11** [contentful/contentful.net#97]
Hello there,  I am using your SDK for my Xamarin.Forms Project. I will gladly share it when it is done. 

The first issue I got, is that by default Contentful.csharp does not support PCL Library. This is a problem because, at this moment, when you create a Xamarin.Forms Project it creates a PCL Project and not .NetStandard. So the developer must upgrade to NetStandard from PCL which can be problematic. 

The Second issue is that although Contentful.csharp is basically rest requests which would use Json.net and Microsoft Http Client, but I have to install the nuget package and use the client on Android Projects and iOS Projects which raise the need to use DI and containers to call it from the shared Project.  Can you guys have a look at it ? 

Should I keep this as one issue ? or make them into two issues ?

**Comment by daspuru** [comment]
Hi @tombby11, I have just uploaded a test I made for using Contentful with Xamarin.Forms. In my solution it works fine in the PCL. Just check the repo:

[https://github.com/daspuru/contentful-xamarin-forms](url)

**Comment by tombby11** [comment]
Hello there ,  I just tried your code and actually it confirms my issues 

1. You have a netStandard Project and not a Classic PCL that is default at the moment (PCL with profile) 

1. If you remove the contentful nuget package from iOS and Android, then the app would crash , can you try it at your side ?

**Comment by daspuru** [comment]
Hi, I have been working with Xamarin.Forms .NET Standard PCL in several projects with out problems. If the Imports section in project.json is configured ok you can use all NuGet packages and evens share login/models in a PCL with a .NET Core App or API, it is great. 

Also, it is normal to have the Nuget packages in the platform solution as it is the runtime project, I don't see why it have to be other way. The logic for pulling content is all in the PCL.

**Comment by Roblinde** [comment]
Hi Tombby!

Thanks for trying out the SDK, really excited about the use case with Xamarin.Forms. Let me know how it turns out.

I'm sorry to hear you ran into some issues with the PCL, unfortunately we do not have any plans to support PCL as they are being superceded across the board with NetStandard. As soon as NetStandard 2.0 is released this SDK will start supporting that offering an even broader spectrum of compatability.  Going forward this will be the default for Xamarin.Forms apps as well. If you're interested this blog shows how to build Xamarin.Forms apps with NetStandard https://blog.xamarin.com/building-xamarin-forms-apps-net-standard/

Regarding your second issue I'm not quite sure I follow. Contentful.csharp is the nuget package for the SDK which you would have to install to use the SDK, that in turns has two dependenies. Json.Net and NetStandard. The SDK as such is built to support DI well and all of the client classes implement interfaces that you should be able to configure with your DI container.

Hope this helps.

Best

Robert

**Comment by tombby11** [comment]
Thanks Robert for your explanations. 

About the second issue , I want to ask , why do we need to install the nuget packages to the Android and iOS Projects ? Isn't all the used libraries can be only at the PCL level ? Ex. HttpClient , Json.Net ... or do you have special stuff implemented in the iOS and Android side ? 
is it clearer ?

**Comment by Roblinde** [comment]
Ah yes, now I understand what you mean.

You do not necessarily need to install the packages to the iOS or Android projects if you structure your projects in such a way that they have no direct dependency on the Contentful.csharp classes. However as your PCL project will still depend on them they will still be added to the output when those projects are compiled so in the end it won't matter that much I think.

Is there a specific reason you wish to avoid the dependency in the iOS and Android projects?

In the end they would be compiled to native iOS and MonoVM code anyway, right?

**Comment by tombby11** [comment]
Yeah you are right , it is just did not make any sense to me that it does not run unless I have the nuget installed on all the platforms. but anyway it is not a catastrofic issue :)

**Comment by Roblinde** [comment]
Ok, thanks for your feedback. I'll close this issue as I don't think there's much that I can do about these particular problems, but feel free to reach out again if you have anything else that you think could improve the SDK in any way. 

And let us know when we have something cool with Xamarin.Forms built 😃 

Cheers!
